inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/IndentationWidth:
  EnforcedStyle: spaces
  Width: 2

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/VariableName:
  EnforcedStyle: camelCase
